const constants = {
  SET_API_RESPONSE: "SET_API_RESPONSE",
  SET_WINDOW: "SET_WINDOW",
  SET_USER_LOCATION: "SET_USER_LOCATION",
  GET_USER_LOCATION: "GET_USER_LOCATION",
  SET_LOGIN_TOKEN: "SET_LOGIN_TOKEN",
  GET_JOB: "GET_JOB",
  GET_JOBS: "GET_JOBS",
  SET_LOGOUT: "SET_LOGOUT",
  SET_JOB_POST: "SET_JOB_POST",
  GET_USER: "GET_USER"
 }
 export default constants